# Program Overview and Items to be Considered {#summary}

> Kulas note: All of this stuff needs to be transferred to other chapters & overall outline revisited

## Mission Statement  

Our mentor program is dedicated to creating an environment that fosters growth, development and engagement of first year I-O students to become successful both academically and socially during graduate school. 

* develop
* engagement
* support
* social

## Program

1) Students who have already taken the fall classes can be mentors
2) Mentors have to go through a “training” (review developed handbook)
3) Must have a certain GPA (3.0)
4) Sending out blast email to program each semester
5) Provide bio? **(maybe this part shouldnt be part of the handbook, but a nice addition to the active program)**
    + Undergraduate degree: 
    + I/O interests
    + Current research
    + Favorite MSU I/O class 
    + After graduation: Anything else

## Creating Handbook

## Responsibilities

### Mentor  

* How many meetings required per month (one meeting a month)
* Text check ups between meetings(based on rapport with mentee)
* Attending program activities with mentees  

### Mentee  

* Reach out to mentor and maintain communication
* Attend Program activities with Mentor
* Seek academic advice and or guidance from Mentor 

**(Kristina and Delia and I have populated and expanded in Monday App)**

## Creating Social Calendar
* First Meeting: First week of school
    + Formal meeting to introduce mentor/mentees overview of the program
    + Move to (Alexis?) and have an informal social gathering post meeting

**(Nishi has already populated but we can still formulate future activities )**

## Program characteristics:
1) Study groups?
2) X times per semester formal meeting (all mentors/mentees)
3) Office hours (mentees to drop by and can ask questions [non threatening environment])
4) Having a goal-oriented objectives
5) Phases 1 (pre-semester)/ Phase 2 (
6) Having an exit survey from the mentees 

## Incentives: 
* resume (mentor) - events exclusive to program participants?
    + Resume booster
* Social events to meet new friends and build relationships
    + Get to know 2nd year students
* Networking within cohort and within program
* OCBs
* Program/ community building
* Application of what we been learning (ex. Motivation theories,goal setting theory)

## Creating a Tradition
* Could be the baseball game 
* Could be an I-O specific tradition (ideas?)

## Program Director?
* A non mentor director so students don’t feel uncomfortable discussing anything about a mentor or possibly opting out of the program 
